services:
  - type: web
    name: rara-pt-webapp
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "npm start"
    healthCheckPath: /healthz
    envVars:
      - key: HOST
        value: 0.0.0.0
